html-report: --format progress --format html --out=report/features_report.html
test: --tags @test
allure: "--format pretty --color --format AllureCucumber::CucumberFormatter --out report/allure-results"
